---
apiVersion: v1
kind: Pod
metadata:
  name: debian-nginx-pod
spec:
  containers:
  - name: debian-container
    image: debian
    command: ["sh", "-c", "while true; do date > /html/index.html; sleep 1; done"]
    volumeMounts:
    - name: html-volume
      mountPath: /html
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    emptyDir: {}
