---
apiVersion: batch/v1
kind: Job
metadata:
  name: gsutil-sync-job
spec:
  template:
    spec:
      containers:
      - name: gsutil-sync-container
        image: google/cloud-sdk:latest
        command:
        - "/bin/sh"
        - "-c"
        - "gsutil -m rsync -r gs://glow-sportradar /data/input"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: glow-data-disk-200
