---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
  - name: app-container
    image: demo/app:1.0.0
    ports:
    - containerPort: 8000
      protocol: TCP
